all:
  infra_vlan: 3301
  kubeapi_vlan: 3
  service_vlan: 202
  network_interfaces:
   node:
     mtu: 1500
   opflex:
     mtu: 1700
  os_compute_nodes:
   node_network_interface:
     - ens2
     - ens3 
   aci_infra_network_interface:
     - ens4
     - ens5
  os_cp_nodes:
   node_network_interface:
     - ens1f0
     - ens1f1
   aci_infra_network_interface:
     - ens1f2
     - ens1f3